// Generated by tools/sync-devtools-devices.mjs from Chrome DevTools' device list
// (devtools-frontend/front_end/models/emulation/EmulatedDevices.ts). Do not edit by hand.
//
// Copyright 2014 The Chromium Authors. Redistribution and use in source and binary forms,
// with or without modification, are permitted provided that the following conditions are
// met: redistributions of source code must retain the above copyright notice, this list of
// conditions and the following disclaimer; redistributions in binary form must reproduce
// the above copyright notice, this list of conditions and the following disclaimer in the
// documentation and/or other materials provided with the distribution; neither the name of
// Google LLC nor the names of its contributors may be used to endorse or promote products
// derived from this software without specific prior written permission.
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
// THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
// OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
// TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/** @typedef {{ id: string, label: string, group: string, w: number, h: number, dpr: number,
 *   rotates: boolean, mobile: boolean,
 *   insets?: { top: number, right: number, bottom: number, left: number },
 *   cutout?: { shape: string, x: number, y: number, width: number, height: number, 'border-radius'?: number } }} EmulatedDevice */

export const DEVTOOLS_GROUPS = ["iPhone","Android","Foldable","Tablet","Laptop & display"];

/** @type {EmulatedDevice[]} */
export const DEVTOOLS_DEVICES = [
  {"id":"iphone-se","label":"iPhone SE","group":"iPhone","w":375,"h":667,"dpr":2,"rotates":true,"mobile":true},
  {"id":"iphone-xr","label":"iPhone XR","group":"iPhone","w":414,"h":896,"dpr":2,"rotates":true,"mobile":true,"insets":{"left":0,"top":44,"right":0,"bottom":34},"cutout":{"shape":"notch","x":92,"y":0,"width":231,"height":33,"upper-radius":6,"lower-radius":25}},
  {"id":"iphone-12-pro","label":"iPhone 12 Pro","group":"iPhone","w":390,"h":844,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":47,"right":0,"bottom":34},"cutout":{"shape":"notch","x":90,"y":0,"width":210,"height":32,"upper-radius":6,"lower-radius":23}},
  {"id":"iphone-14","label":"iPhone 14","group":"iPhone","w":390,"h":844,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":47,"right":0,"bottom":34},"cutout":{"shape":"notch","x":114,"y":0,"width":162,"height":34,"upper-radius":5,"lower-radius":22}},
  {"id":"iphone-14-plus","label":"iPhone 14 Plus","group":"iPhone","w":428,"h":926,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":47,"right":0,"bottom":34},"cutout":{"shape":"notch","x":133,"y":0,"width":161,"height":34,"upper-radius":5,"lower-radius":22}},
  {"id":"iphone-14-pro","label":"iPhone 14 Pro","group":"iPhone","w":393,"h":852,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":59,"right":0,"bottom":34},"cutout":{"shape":"pill","x":134,"y":11,"width":125,"height":37,"border-radius":19}},
  {"id":"iphone-14-pro-max","label":"iPhone 14 Pro Max","group":"iPhone","w":430,"h":932,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":59,"right":0,"bottom":34},"cutout":{"shape":"pill","x":153,"y":11,"width":125,"height":37,"border-radius":19}},
  {"id":"iphone-15","label":"iPhone 15","group":"iPhone","w":393,"h":852,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":59,"right":0,"bottom":34},"cutout":{"shape":"pill","x":134,"y":11,"width":125,"height":37,"border-radius":19}},
  {"id":"iphone-15-plus","label":"iPhone 15 Plus","group":"iPhone","w":430,"h":932,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":59,"right":0,"bottom":34},"cutout":{"shape":"pill","x":153,"y":11,"width":125,"height":37,"border-radius":19}},
  {"id":"iphone-15-pro","label":"iPhone 15 Pro","group":"iPhone","w":393,"h":852,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":59,"right":0,"bottom":34},"cutout":{"shape":"pill","x":134,"y":11,"width":125,"height":37,"border-radius":19}},
  {"id":"iphone-15-pro-max","label":"iPhone 15 Pro Max","group":"iPhone","w":430,"h":932,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":59,"right":0,"bottom":34},"cutout":{"shape":"pill","x":153,"y":11,"width":125,"height":37,"border-radius":19}},
  {"id":"iphone-16e","label":"iPhone 16e","group":"iPhone","w":390,"h":844,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":47,"right":0,"bottom":34},"cutout":{"shape":"notch","x":114,"y":0,"width":162,"height":34,"upper-radius":5,"lower-radius":22}},
  {"id":"iphone-16","label":"iPhone 16","group":"iPhone","w":393,"h":852,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":59,"right":0,"bottom":34},"cutout":{"shape":"pill","x":134,"y":11,"width":125,"height":37,"border-radius":19}},
  {"id":"iphone-16-plus","label":"iPhone 16 Plus","group":"iPhone","w":430,"h":932,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":59,"right":0,"bottom":34},"cutout":{"shape":"pill","x":153,"y":11,"width":125,"height":37,"border-radius":19}},
  {"id":"iphone-16-pro","label":"iPhone 16 Pro","group":"iPhone","w":402,"h":874,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":62,"right":0,"bottom":34},"cutout":{"shape":"pill","x":139,"y":14,"width":125,"height":37,"border-radius":19}},
  {"id":"iphone-16-pro-max","label":"iPhone 16 Pro Max","group":"iPhone","w":440,"h":956,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":62,"right":0,"bottom":34},"cutout":{"shape":"pill","x":158,"y":14,"width":125,"height":37,"border-radius":19}},
  {"id":"jiophone-2","label":"JioPhone 2","group":"Android","w":240,"h":320,"dpr":1,"rotates":true,"mobile":true},
  {"id":"pixel-7","label":"Pixel 7","group":"Android","w":412,"h":915,"dpr":2.625,"rotates":true,"mobile":true,"insets":{"left":0,"top":52,"right":0,"bottom":0},"cutout":{"shape":"circle","x":183,"y":0,"width":55,"height":52,"cx":206,"cy":26,"radius":13}},
  {"id":"pixel-8","label":"Pixel 8","group":"Android","w":412,"h":915,"dpr":2.625,"rotates":true,"mobile":true,"insets":{"left":0,"top":50,"right":0,"bottom":0},"cutout":{"shape":"circle","x":182,"y":0,"width":46,"height":50,"cx":206,"cy":25,"radius":14}},
  {"id":"pixel-8-pro","label":"Pixel 8 Pro","group":"Android","w":448,"h":997,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":50,"right":0,"bottom":0},"cutout":{"shape":"circle","x":205,"y":0,"width":37,"height":50,"cx":224,"cy":25,"radius":14}},
  {"id":"pixel-8a","label":"Pixel 8a","group":"Android","w":412,"h":915,"dpr":2.625,"rotates":true,"mobile":true,"insets":{"left":0,"top":46,"right":0,"bottom":0},"cutout":{"shape":"circle","x":185,"y":0,"width":42,"height":46,"cx":206,"cy":26,"radius":13}},
  {"id":"pixel-9","label":"Pixel 9","group":"Android","w":412,"h":924,"dpr":2.625,"rotates":true,"mobile":true,"insets":{"left":0,"top":58,"right":0,"bottom":0},"cutout":{"shape":"circle","x":188,"y":0,"width":37,"height":58,"cx":206,"cy":29,"radius":14}},
  {"id":"pixel-9-pro","label":"Pixel 9 Pro","group":"Android","w":427,"h":952,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":68,"right":0,"bottom":0},"cutout":{"shape":"circle","x":195,"y":0,"width":36,"height":68,"cx":213,"cy":34,"radius":16}},
  {"id":"pixel-9-pro-xl","label":"Pixel 9 Pro XL","group":"Android","w":448,"h":997,"dpr":3,"rotates":true,"mobile":true,"insets":{"left":0,"top":66,"right":0,"bottom":0},"cutout":{"shape":"circle","x":205,"y":0,"width":38,"height":66,"cx":224,"cy":33,"radius":16}},
  {"id":"pixel-10","label":"Pixel 10","group":"Android","w":412,"h":924,"dpr":2.625,"rotates":true,"mobile":true,"insets":{"left":0,"top":58,"right":0,"bottom":0},"cutout":{"shape":"circle","x":188,"y":0,"width":37,"height":58,"cx":206,"cy":29,"radius":14}},
  {"id":"samsung-galaxy-s8","label":"Samsung Galaxy S8+","group":"Android","w":360,"h":740,"dpr":4,"rotates":true,"mobile":true},
  {"id":"samsung-galaxy-a55","label":"Samsung Galaxy A55","group":"Android","w":360,"h":800,"dpr":2.25,"rotates":true,"mobile":true},
  {"id":"samsung-galaxy-s20-ultra","label":"Samsung Galaxy S20 Ultra","group":"Android","w":412,"h":915,"dpr":3.5,"rotates":true,"mobile":true},
  {"id":"samsung-galaxy-a51-71","label":"Samsung Galaxy A51/71","group":"Android","w":412,"h":914,"dpr":2.625,"rotates":true,"mobile":true},
  {"id":"facebook-on-android","label":"Facebook on Android","group":"Android","w":412,"h":892,"dpr":3.5,"rotates":true,"mobile":true},
  {"id":"moto-g4","label":"Moto G4","group":"Android","w":360,"h":640,"dpr":3,"rotates":true,"mobile":true},
  {"id":"moto-g-power","label":"Moto G Power","group":"Android","w":412,"h":823,"dpr":1.75,"rotates":true,"mobile":true},
  {"id":"surface-duo","label":"Surface Duo","group":"Foldable","w":540,"h":720,"dpr":2.5,"rotates":true,"mobile":true},
  {"id":"pixel-9-pro-fold","label":"Pixel 9 Pro Fold","group":"Foldable","w":412,"h":922,"dpr":2.625,"rotates":true,"mobile":true},
  {"id":"galaxy-z-fold-6","label":"Galaxy Z Fold 6","group":"Foldable","w":412,"h":968,"dpr":2.625,"rotates":true,"mobile":true},
  {"id":"galaxy-z-fold-5","label":"Galaxy Z Fold 5","group":"Foldable","w":344,"h":882,"dpr":2.625,"rotates":true,"mobile":true},
  {"id":"asus-zenbook-fold","label":"Asus Zenbook Fold","group":"Foldable","w":853,"h":1280,"dpr":1.5,"rotates":true,"mobile":false},
  {"id":"ipad-mini","label":"iPad Mini","group":"Tablet","w":768,"h":1024,"dpr":2,"rotates":true,"mobile":true},
  {"id":"ipad-pro-13","label":"iPad Pro 13","group":"Tablet","w":1032,"h":1376,"dpr":2,"rotates":true,"mobile":true},
  {"id":"surface-pro-7","label":"Surface Pro 7","group":"Tablet","w":912,"h":1368,"dpr":2,"rotates":true,"mobile":true},
  {"id":"surface-pro-10","label":"Surface Pro 10","group":"Tablet","w":960,"h":1440,"dpr":2,"rotates":true,"mobile":true},
  {"id":"galaxy-tab-s4","label":"Galaxy Tab S4","group":"Tablet","w":712,"h":1138,"dpr":2.25,"rotates":true,"mobile":true},
  {"id":"nest-hub-max","label":"Nest Hub Max","group":"Laptop & display","w":1280,"h":800,"dpr":2,"rotates":false,"mobile":true},
  {"id":"laptop-with-touch","label":"Laptop with touch","group":"Laptop & display","w":1280,"h":950,"dpr":1,"rotates":false,"mobile":false},
  {"id":"laptop-with-hidpi-screen","label":"Laptop with HiDPI screen","group":"Laptop & display","w":1440,"h":900,"dpr":2,"rotates":false,"mobile":false},
  {"id":"laptop-with-mdpi-screen","label":"Laptop with MDPI screen","group":"Laptop & display","w":1280,"h":800,"dpr":1,"rotates":false,"mobile":false},
];
